In [1]:
import pandas as pd
import altair as alt

In [2]:
round2 = pd.read_csv("../data/persuasion-game/round2.csv")

In [3]:
round2.head()

   Unnamed: 0          X          Y
0           1  18.541982  47.512030
1           2  19.629819  42.924723
2           3  15.591767  68.464286
3           4  12.288314  64.984829
4           5  15.472194  67.730696

Can you show me a distribution of X and Y showing the potential outliers?

In [4]:
chart1 = alt.Chart(round2).mark_bar().encode(
    alt.X("X:Q", bin=True),
    y='count()',
)

chart2 = alt.Chart(round2).mark_bar().encode(
    alt.X("Y:Q", bin=True),
    y='count()',
)

chart1 | chart2

alt.HConcatChart(...)

In [5]:
chart1 = alt.Chart(round2).mark_bar().encode(
    alt.X("X:Q", bin=alt.Bin(maxbins=20)),
    y='count()',
)
chart1

alt.Chart(...)

In [6]:
round3 = pd.read_csv("../data/persuasion-game/round3.csv")
round3.head()

   Unnamed: 0  year        sales
0           1  1975   948.381993
1           2  1976  6074.594700
2           3  1977  1266.752346
3           4  1978  1087.824106
4           5  1984  7028.915075

In [7]:
alt.Chart(round3).mark_line(
    point=True
).encode(
    x=alt.X('year:N', 
            axis=alt.Axis(
                values=[1975, 1984, 2000, 2006, 2024]  
            )),
    y=alt.Y('sales:Q')
).transform_filter(
    alt.FieldOneOfPredicate(
        field='year', 
        oneOf=[1975, 1984, 2000, 2006, 2024]
    )
).properties(
    width=600,
    height=400
)

alt.Chart(...)

In [8]:
import altair as alt

In [9]:
round4 = pd.read_csv("../data/persuasion-game/round4.csv")

In [10]:
round4

       Unnamed: 0  Major Gender Admission
0               1      C      F  Rejected
1               2      B      M  Accepted
2               3  Other      F  Accepted
3               4  Other      M  Accepted
4               5  Other      M  Rejected
...           ...    ...    ...       ...
12758       12759  Other      M  Accepted
12759       12760      D      M  Accepted
12760       12761  Other      F  Rejected
12761       12762  Other      M  Rejected
12762       12763  Other      M  Accepted

[12763 rows x 4 columns]

In [12]:
alt.data_transformers.disable_max_rows()
alt.Chart(round4).mark_bar().encode(
    x='Major:N',
    y=alt.Y('count():Q', axis=None),
    color='Admission:N',
    column='Gender:N'  
)

alt.Chart(...)

In [15]:
base = alt.Chart(round4).transform_aggregate(
    count='count()',
    groupby=['Gender', 'Major', 'Admission']
).transform_joinaggregate(
    total='sum(count)',
    groupby=['Gender', 'Major']
).transform_calculate(
    percentage='100 * datum.count / datum.total'
)

# Create the visualization
base.mark_bar().encode(
    x='Major:N',
    y=alt.Y('percentage:Q', title='Percentage'),
    color='Admission:N',
    column='Gender:N'
)

alt.Chart(...)